<a href="https://colab.research.google.com/github/khaireddine-satouri/10-Applied-Data-Science-Capstone/blob/main/TP2_Kheireddine_SATOURI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercice 1

Créer	un	tableau	depuis	la	liste [1.6, 0.5, 7.4, 22.3]	et	stocker	le	dans la	variable	« vec »

In [1]:
import numpy as np

In [2]:
l=[1.6, 0.5, 7.4, 22.3]
vec=np.array(l)

In [3]:
# Afficher	le	contenu	de	la	variable	« vec »
vec

array([ 1.6,  0.5,  7.4, 22.3])

In [4]:
# Afficher	le	type	de	données	du	tableau	« vec »,	sa	forme,	sa	dimension	et	sa longueur.
print(f"type : {vec.dtype}")
print(f"forme : {vec.shape}")
print(f"dimension : {vec.ndim}")
print(f"dimension : {len(vec)}")

type : float64
forme : (4,)
dimension : 1
dimension : 4


In [5]:
# Afficher	le	troisième	élément	du	tableau.
vec[3]

22.3

In [6]:
# Modifier	la	valeur	« 0.5 »	par	« 3.8 ».
vec[1]=3.8
vec

array([ 1.6,  3.8,  7.4, 22.3])

In [7]:
# Calculer la	taille	de	la	mémoire	du	tableau.
print("La taille de la mémoire du tableau est : ", vec.nbytes)

La taille de la mémoire du tableau est :  32


In [8]:
# Convertir	le	type	du	tableau	vers	« int	»
vec=vec.astype(int)
vec.dtype

dtype('int64')

In [9]:
# Calculer la taille de la mémoire du tableau après la conversion
print("La taille de la mémoire du tableau après la conversion est : ", vec.nbytes)

La taille de la mémoire du tableau après la conversion est :  32


In [10]:
# Sauvegarder le tableau dans un fichier texte
np.savetxt("vec.txt", vec)

Créer	une	matrice	« mat »	depuis	la	liste	[[0,	3,	6,	9],	[5,	10,	15,	20],	[30,	40,	50,	60]]


In [11]:
l2= [[0, 3, 6, 9], [5, 10, 15, 20], [30, 40, 50, 60]]
mat=np.array(l2)

In [12]:
# Afficher	le	contenu	de	la	variable	« mat »
print(mat)

[[ 0  3  6  9]
 [ 5 10 15 20]
 [30 40 50 60]]


In [13]:
# Afficher	le	type	de	données	du	tableau	« vec »,	sa	forme,	sa	dimension	et	sa longueur.
print(f"type : {mat.dtype}")
print(f"forme : {mat.shape}")
print(f"dimension : {mat.ndim}")
print(f"longueur : {len(mat)}")

type : int64
forme : (3, 4)
dimension : 2
longueur : 3


In [14]:
# Pouvez-vous	obtenir	la	dimension	et	la longueur à	partir	de	la	forme	?
shape=mat.shape
# Obtenir la forme du tableau
print("Forme : ", shape)
# Obtenir la dimension du tableau
print("Dimension : ", len(shape))
# Afficher les résultats
print("Longueur : ", shape[0])

Forme :  (3, 4)
Dimension :  2
Longueur :  3


In [15]:
# Créer	la	matrice	« mat_1 » extraite	de	« mat » telles que	i	>=	1,	j	<=2.	
mat_1 = mat[1:, :2]
print(mat_1)

[[ 5 10]
 [30 40]]


In [16]:
# Modifier	la	matrice	« mat »	afin	que	sa dernière	ligne	soit	divisée	par	10	et	que	sa	première	colonne	soit	multipliée par	2.	
# Diviser la dernière ligne de mat par 10
mat[-1, :] = mat[-1, :] / 10

# Multiplier la première colonne de mat par 2
mat[:, 0] = mat[:, 0] * 2

# Afficher mat
print(mat)

[[ 0  3  6  9]
 [10 10 15 20]
 [ 6  4  5  6]]


Créer	un	tableau	multidimensionnel	« nd_vec	»	d’une	dimension	>	2	


In [17]:
# Créer nd_vec, un tableau multidimensionnel de 3 dimensions de taille (2, 3, 4)
nd_vec = np.random.rand(2, 3, 4)

In [18]:
# Afficher nd_vec
print(nd_vec)

[[[0.01260229 0.52971239 0.10562555 0.06608079]
  [0.33356402 0.35537071 0.27313671 0.40887701]
  [0.0113713  0.80730952 0.47454934 0.47840984]]

 [[0.70757288 0.41423727 0.04519822 0.58977134]
  [0.37602461 0.25174387 0.16179851 0.55915161]
  [0.66974955 0.59548254 0.68774589 0.31011457]]]


In [19]:
# Afficher le type de données, la forme, la dimension et la longueur de nd_vec
print("Type de données :", nd_vec.dtype)
print("Forme :", nd_vec.shape)
print("Dimension :", nd_vec.ndim)
print("Longueur :", len(nd_vec))

Type de données : float64
Forme : (2, 3, 4)
Dimension : 3
Longueur : 2


In [20]:
# La dimension et la longueur peuvent être obtenues à partir de la forme :
print("Dimension :", nd_vec.shape[0])
print("Longueur :", nd_vec.shape[1])

Dimension : 2
Longueur : 3


In [21]:
# Afficher un élément de nd_vec
print("Élément (1, 2, 3) :", nd_vec[1, 2, 3])
print("Élément (1, 2, 3) :", nd_vec[1][2][3]) # pareil

Élément (1, 2, 3) : 0.31011456816811545
Élément (1, 2, 3) : 0.31011456816811545


# Exercice 2

In [22]:
# Créer un	 tableau	1D	vide	de	 taille	10	et	de	 type	« int » ;	observer les	valeurs	du tableau.
tab_vide=np.empty(10,dtype=int)
tab_vide  #Le tableau n’est pas initialisé « valeurs arbitraires »

array([           42669024,                   0,                   0,
                         0,                   0, 3762023226263222581,
       7004273009887633709, 3270518448247891556, 7147833163533922865,
           139690479334245])

In [23]:
# Créer	 un	 tableau	2D	 vide	 de	 dimension	 (3*3)	 et	 de	 type	 « float » ; observer les valeurs	du	tableau.
arr = np.empty((3, 3), dtype=float)
print(arr)

[[2.10813463e-316 0.00000000e+000 7.90505033e-323]
 [2.12765615e-316 0.00000000e+000 0.00000000e+000]
 [9.88131292e-324 0.00000000e+000 1.18575755e-321]]


In [24]:
# Créer	un	tableau	de	3	dimensions	(3*3*3)	initialisé	avec	des	zéros	« 0 ».
tab_0=np.zeros((3,3,3))
tab_0

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
# Créer	une	matrice	de	taille	(5*5) comportant	des	uns	« 1 ».
tab_1=np.ones((5,5))
tab_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Créer	un	tableau	de	taille	(10*10)	initialisé	avec	la	valeur	« np.inf ».
tab_inf=np.full((10,10),np.inf)
tab_inf

array([[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]])

In [27]:
# Créer	une	matrice	d’identité	de	taille	(4*4)
np_id=np.identity(4)
np_id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Créer	une	matrice dont	la	diagonale	est	égale	à	[2,	3,	4,	5]	et	des	0	ailleurs.
diag=[2,	3,	4,	5]
tab_diag=np.diag(diag)
tab_diag

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

# Exercice	3 

In [29]:
# Créer	un	tableau	comportant	la	série	d’entiers	de	5	à	25 :	[5,	6,	7,	...	,	23,24,25]
serie1=np.linspace(5,25,21,dtype=int)
serie1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [30]:
# Créer	un	tableau	contenant	tous	les	entiers	pairs	entre	100	et	150	inclus.
serie2 = np.arange(100, 151, 2)
serie2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [31]:
# Créer	un	tableau	qui	comporte	les	dates	du	mois	de	Février	2019,	ce	tableau	est	de type	« datetime64[D] »
start_date = np.datetime64('2019-02-01')
end_date = np.datetime64('2019-03-01')
dates = np.arange(start_date, end_date, dtype='datetime64[D]')
dates

array(['2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
       '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08',
       '2019-02-09', '2019-02-10', '2019-02-11', '2019-02-12',
       '2019-02-13', '2019-02-14', '2019-02-15', '2019-02-16',
       '2019-02-17', '2019-02-18', '2019-02-19', '2019-02-20',
       '2019-02-21', '2019-02-22', '2019-02-23', '2019-02-24',
       '2019-02-25', '2019-02-26', '2019-02-27', '2019-02-28'],
      dtype='datetime64[D]')

In [32]:
# Créer	un	tableau	de	dix	éléments	équidistants	entre	2	et	5	inclus.
arr=np.linspace(2,5,10)
arr

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [33]:
# Soit	la	fonction	y	=	f(x)=	(ex – e-x)/(ex + e-x).	Créer	des	tableaux	x,	y	qui	contiennent	respectivement	50	valeurs	réparties	uniformément	sur	[-5,	5]	et	l’évaluation	de	la	fonction	sur	ces	valeurs
def f(x):
  return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
x=np.linspace(-5,5,50)
f(x)

array([-0.9999092 , -0.99986344, -0.99979462, -0.99969111, -0.99953545,
       -0.99930137, -0.99894941, -0.99842027, -0.99762495, -0.99642993,
       -0.99463525, -0.99194203, -0.98790496, -0.9818637 , -0.97284617,
       -0.9594368 , -0.93960819, -0.91052931, -0.86839883, -0.80841907,
       -0.72512414, -0.61335726, -0.47010419, -0.29690545, -0.10168812,
        0.10168812,  0.29690545,  0.47010419,  0.61335726,  0.72512414,
        0.80841907,  0.86839883,  0.91052931,  0.93960819,  0.9594368 ,
        0.97284617,  0.9818637 ,  0.98790496,  0.99194203,  0.99463525,
        0.99642993,  0.99762495,  0.99842027,  0.99894941,  0.99930137,
        0.99953545,  0.99969111,  0.99979462,  0.99986344,  0.9999092 ])

In [34]:
# Écrire un	programme	NumPy	qui	permet	de	générer	un	nombre	aléatoire	entre	0	et	1
gen=np.random.rand()
gen

0.993551172055831

In [35]:
# Créer	un	tableau	de	la	dimension	et	de	la	taille	de	votre	choix	contenant	des	valeurs entre	34	et	76.
tab = np.random.randint(34, 77, size=(3, 4))
tab

array([[59, 48, 34, 45],
       [66, 52, 69, 76],
       [58, 52, 45, 48]])

In [36]:
# Faites	 un	 tableau	 de	 forme (3,	 5)	 avec	 des	 nombres	 aléatoires	 à	 partir	 d'une distribution	normale	standard	(une	distribution	normale	avec	une	moyenne	0	et une	variance	1).
dis_norm=np.random.normal(size=(3,5))
dis_norm

array([[ 0.65453686,  0.79029538, -0.00841558, -1.13440501, -0.19340429],
       [ 0.7759224 , -0.6549044 , -1.3175287 , -1.70901314,  1.97067914],
       [ 1.44947541,  0.15226679, -0.87524691,  0.52832992,  0.7273952 ]])

In [37]:
# Créer	une	matrice (10x5)	comportant	des	entiers	aléatoires	entre	0	et	100.
# Standardiser cette	 matrice	 telle	 que	 chaque	 colonne	 aura une	 moyenne	nulle	et	un	écart	type	égal	à	1.	
mat = np.random.randint(0, 101, size=(10, 5))
# Calcul de la moyenne et de l'écart type pour chaque colonne
mean = np.mean(mat, axis=0)
std = np.std(mat, axis=0)

# Standardisation de la matrice
mat_std = (mat - mean) / std
mat_std

array([[-0.28619139, -0.19474367,  0.18095068, -0.84161151,  1.19837006],
       [ 1.19300005,  0.40141042, -1.22644349, -0.30955826,  1.11153165],
       [ 1.4180944 ,  0.8385901 , -0.5830633 ,  1.04475912, -1.14626701],
       [-0.60775474,  0.75910288,  2.23172504,  1.14149607,  0.32998596],
       [-1.50813214, -1.70500071,  0.02010563, -0.74487456,  1.15495085],
       [ 1.00006204,  1.43474419,  0.54285204,  0.17412652, -0.88575178],
       [-0.80069276, -1.26782104,  0.90475339, -2.05082346,  1.02469324],
       [-1.02578711, -0.91012859, -0.50264077,  0.70617977, -1.0160094 ],
       [-0.38266039,  0.99756452, -0.2613732 ,  1.18986455, -0.62523655],
       [ 1.00006204, -0.3537181 , -1.30686601, -0.30955826, -1.14626701]])

# Exercice 4



```
# Ce texte est au format code
```

Créer	une	matrice	aléatoire	10x10.


In [38]:
mat= np.random.randn(10, 10)
mat

array([[ 0.84742893,  1.38894149,  0.7049113 , -0.527861  , -0.14360296,
        -1.91099106, -0.21476562, -0.58148615,  0.13019855, -0.42313761],
       [ 0.03786857,  0.81084638, -0.552023  ,  0.41311868,  0.270342  ,
         0.24913345, -1.21213596,  0.51006667,  0.26580786, -1.34623193],
       [-1.79248922,  0.02332697,  0.18537084,  0.31006193, -0.55101885,
         0.2049711 , -0.15783597,  1.87558327,  1.70067076,  1.1317642 ],
       [ 0.73223047, -0.15583288,  3.38686504, -0.53136328,  0.27790884,
        -2.09694815, -1.20449048, -0.51564868, -0.14975646, -1.51295448],
       [-2.30428309,  0.0402952 , -0.22090643, -0.46121164,  1.17272871,
        -1.18390486, -0.85311648,  1.71017155,  0.84916654,  1.60897626],
       [-0.90849465,  0.12959332, -0.33647811, -0.96612244,  1.32317238,
         0.15316132,  0.20782709, -0.02687101,  0.95409362,  0.66721771],
       [-0.430066  ,  0.73135433,  0.10589446, -1.36717594, -1.30051942,
         1.76578152,  0.06125775,  0.96420773

In [39]:
# Sélectionner	l'élément	dans	la	première	ligne	et	la	première	colonne.
mat[0,0]

0.8474289295951855

In [40]:
# Mettre l'élément	de	la	dernière	ligne	et	de	la	dernière	colonne	à	-1.
mat[-1,-1]=-1

In [41]:
# Sélectionner les	éléments	de	la	deuxième	ligne
mat[1,:]

array([ 0.03786857,  0.81084638, -0.552023  ,  0.41311868,  0.270342  ,
        0.24913345, -1.21213596,  0.51006667,  0.26580786, -1.34623193])

In [42]:
# Sélectionner	les	éléments	de la	troisième	colonne
mat[:,2]

array([ 0.7049113 , -0.552023  ,  0.18537084,  3.38686504, -0.22090643,
       -0.33647811,  0.10589446,  0.15958445, -1.73136921,  0.81989902])

In [43]:
# Remplacer tous	les	éléments	de	la	deuxième	ligne	par	0.
mat[1,:]=0

In [44]:
# Écrire un	 programme	 NumPy	 pour	 inverser	 un	 tableau	 (le	 premier	 élément devient	le	dernier).
arr = np.array([1, 2, 3, 4, 5])

# Inverser le tableau
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [45]:
# Écrire	un	programme	NumPy	pour	créer	un	tableau	2d	avec	1	sur	la	bordure	et	0	à	l'intérieur.
# Créer un tableau 2D de 5x5 rempli de 0
arr = np.zeros((5, 5))

# Utiliser la fonction np.pad pour ajouter des bords de 1
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)

print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [46]:
# Écrire un	programme	NumPy	pour	créer	une	matrice	8x8	et	remplissez-la	avec	un	motif	en	damier.
# Création de la matrice 8x8 remplie de 0
matrix = np.zeros((8, 8), dtype=int)

# Remplissage des cases en damier avec des 1
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

# Affichage de la matrice
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercice 5

Écrire	un	programme	NumPy	dans	lequel vous	allez :


In [47]:
# Définir un tableau de 50 éléments aléatoires entre 0 et 100
tableau = np.random.randint(0, 100, 50)

In [50]:
# Calculer	l’écart	type	des	valeurs	présentes	dans	ce	tableau.
ecart_type = np.std(tableau)
ecart_type

29.090816420306943

In [65]:
# Chercher les valeurs et les indices des éléments qui sont supérieurs à la moyenne des valeurs + 1.96 l'écart type
moyenne_plus = np.mean(tableau) + 1.96 * ecart_type
indices_sup = np.where(tableau > moyenne_plus)[0]
valeurs_sup = tableau[indices_sup]
# Remplacer toutes ces valeurs par la valeur maximale du tableau
tableau[indices_sup] = np.max(tableau)

In [66]:
# Chercher les valeurs et les indices des éléments qui sont inférieurs à la moyenne des valeurs - 1.96 l'écart type
moyenne_moins = np.mean(tableau) - 1.96 * ecart_type
indices_inf = np.where(tableau < moyenne_moins)[0]
valeurs_inf = tableau[indices_inf]
# Remplacer toutes ces valeurs par la valeur minimale du tableau
tableau[indices_inf] = np.min(tableau)

In [67]:
# Compter le nombre d'éléments égaux au maximum et le nombre d'éléments égaux au minimum
nombre_max = np.count_nonzero(tableau == np.max(tableau))
nombre_min = np.count_nonzero(tableau == np.min(tableau))

In [68]:
# Compter le nombre d'éléments différents de min ou de max
nombre_diff = np.count_nonzero((tableau != np.min(tableau)) & (tableau != np.max(tableau)))

In [69]:
# Afficher les résultats
print("Tableau initial : ", tableau)
print("L'écart type est : ", ecart_type)
print("Indices des valeurs supérieures à la moyenne + 1.96*écart type : ", indices_sup)
print("Valeurs supérieures à la moyenne + 1.96*écart type : ", valeurs_sup)
print("Indices des valeurs inférieures à la moyenne - 1.96*écart type : ", indices_inf)
print("Valeurs inférieures à la moyenne - 1.96*écart type : ", valeurs_inf)
print("Nombre d'éléments égaux au maximum : ", nombre_max)
print("Nombre d'éléments égaux au minimum : ", nombre_min)
print("Nombre d'éléments différents de min ou de max : ", nombre_diff)

Tableau initial :  [27 97 69  4 28 72 56 91 24 73 17 46 55 34  1 76 82  2 46 72 33 48 11 22
 54 26 57 25  7 85 21 90 62 43  8 97 67  5 43 55  0 80 12 47 46 78  6 25
 69 87]
L'écart type est :  29.090816420306943
Indices des valeurs supérieures à la moyenne + 1.96*écart type :  []
Valeurs supérieures à la moyenne + 1.96*écart type :  []
Indices des valeurs inférieures à la moyenne - 1.96*écart type :  []
Valeurs inférieures à la moyenne - 1.96*écart type :  []
Nombre d'éléments égaux au maximum :  2
Nombre d'éléments égaux au minimum :  1
Nombre d'éléments différents de min ou de max :  47


# Exercice	6 

In [71]:
#Écrire	un	programme	NumPy	pour	créer	une	matrice	3x3	avec	des	valeurs	allant de	2	à	10
matrice = np.arange(2, 11).reshape(3, 3)
print(matrice)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [72]:
matrice = np.arange(1, 16).reshape(3, 5).T
print(matrice)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [73]:
# Diviser le tableau « s = np.arange(25).reshape(5,5) » afin de séparer chaque colonne à part
s = np.arange(25).reshape(5, 5)
colonnes = np.hsplit(s, s.shape[1])
for colonne in colonnes:
    print(colonne)

[[ 0]
 [ 5]
 [10]
 [15]
 [20]]
[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


In [74]:
#matrice en concaténant 3 tableaux unidimensionnels
a = np.array([7, 8, 9])
b = np.ones(3)
c = np.array([12, 18, 2])
matrice = np.vstack((a, b, c))
print(matrice)

[[ 7.  8.  9.]
 [ 1.  1.  1.]
 [12. 18.  2.]]


# Exercice	7

In [75]:
# Trouver les positions des éléments non nuls dans un tableau
arr = np.array([0, 1, 0, 2, 3, 0, 4, 0])
non_zero_positions = np.nonzero(arr)[0]
print(non_zero_positions)

[1 3 4 6]


In [76]:
# Tester si aucun des éléments d'un tableau donné n'est nul
arr = np.array([1, 2, 3, 4])
no_zeros = np.all(arr != 0)
print(no_zeros)

True


In [77]:
# Ajouter une bordure (remplie de 0) autour d'un tableau existant
arr = np.ones((3, 3))
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [78]:
#Créer un tableau à partir d'un tuple ou d'une liste
my_tuple = (1, 2, 3, 4)
my_list = [5, 6, 7, 8]

arr_from_tuple = np.asarray(my_tuple)
arr_from_list = np.asarray(my_list)

print(arr_from_tuple)
print(arr_from_list)

[1 2 3 4]
[5 6 7 8]


In [79]:
# Ajouter des éléments à la fin d'un tableau
arr = np.array([1, 2, 3])
arr_with_elements = np.append(arr, [4, 5, 6])
print(arr_with_elements)

[1 2 3 4 5 6]


In [80]:
# Tester si chaque élément d'un tableau 1-D est également présent dans un second tableau
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4, 5])

in_arr1 = np.in1d(arr1, arr2)
print(in_arr1)

[False  True  True]


In [81]:
#Trouver des valeurs communes entre deux tableaux
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4, 5])

common_values = np.intersect1d(arr1, arr2)
print(common_values)

[2 3]


In [82]:
#Construire un tableau en répétant les éléments d'un autre tableau en utilisant	la	fonction « np.tile »
arr = np.array([1, 2, 3])
tiled_arr = np.tile(arr, (2, 3))
print(tiled_arr)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [83]:
#Utiliser	la	fonction	« bincount	»	pour	compter	le	nombre	d’occurrences	de	chaque	valeur	d’un	tableau	de	valeurs	positives.
arr = np.array([1, 2, 2, 3, 3, 3])
counts = np.bincount(arr)

print(counts)

[0 1 2 3]


# Exercice 8

In [84]:
# Lire le fichier CSV dans un tableau
donnees = np.genfromtxt('titanic.csv', delimiter=',', skip_header=1)

In [85]:
# Afficher le type de la variable donnees
print(type(donnees)) 

<class 'numpy.ndarray'>


In [86]:
# Afficher la dimension du tableau
print(donnees.ndim)  

2


In [87]:
# Afficher la forme du tableau
print(donnees.shape)  

(891, 13)


In [88]:
# Afficher les cinq premières lignes du tableau
print(donnees[:5, :])

[[1.00000e+00 0.00000e+00 3.00000e+00         nan         nan         nan
  2.20000e+01 1.00000e+00 0.00000e+00         nan 7.25000e+00         nan
          nan]
 [2.00000e+00 1.00000e+00 1.00000e+00         nan         nan         nan
  3.80000e+01 1.00000e+00 0.00000e+00         nan 7.12833e+01         nan
          nan]
 [3.00000e+00 1.00000e+00 3.00000e+00         nan         nan         nan
  2.60000e+01 0.00000e+00 0.00000e+00         nan 7.92500e+00         nan
          nan]
 [4.00000e+00 1.00000e+00 1.00000e+00         nan         nan         nan
  3.50000e+01 1.00000e+00 0.00000e+00 1.13803e+05 5.31000e+01         nan
          nan]
 [5.00000e+00 0.00000e+00 3.00000e+00         nan         nan         nan
  3.50000e+01 0.00000e+00 0.00000e+00 3.73450e+05 8.05000e+00         nan
          nan]]


In [89]:
# Modifier les données
donnees[0, 0] = 999

In [90]:
# Sauvegarder les nouvelles données dans un fichier CSV
np.savetxt('titanic_mod.csv', donnees, delimiter=',')